development: &default
  adapter: mysql2
  encoding: latin1
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

test:
  <<: *default
  database: my_application_test

integration:
  <<: *default
  reconnect: true

sandbox:
  <<: *default
  reconnect: true

production:
  <<: *default
  reconnect: true
